sudo: required
services:
- docker
script:
- docker build -t $DOCKER_IMAGE .
notifications:
  slack:
    secure: DXQ3HZenRklXGszlq7nB5wfmH2lXT3AouVyznEWG9b4ChrgKBwb1WDaZ/9clY3BbN7GBoJ0i6bx4riMCs3jNBJJqeqvPXoHhVEVzY12UGkNMs6moJ9xw61jNbmg3knaVOITKN7xhun9O1Dh9ebS4J+httGt9lewGDztgdSSs3r0MDWkl5CBBniOHqRMhbPzzjGN6526k7b9NLW9BvU2+oeE3ktQ5RanBP3XKg97kdMU1UDPqU5g0oiyNYV6oTWMO0DLNbIPsqSdSczNxCqHP7/B+IYp9tScWLctUQtDPZOtJCM/Vi7lJ/acJ/EqP8pp07OHnoIKIE3RCLzLYIsOLRTZjVgvebH4IGet6Df/xUc6ZTgCWCuQrOSF2h+jKl3lH7ShTN2o2sfIjFzIm5S1NDGFn+AZPVH6E0aFhMw9yGFqaRdV6209xV92/mNFI2OJi3QwYDRxzJBpBbbfCsmmrluRLRUXpLyzRzhNKFD64MIjpcnE3+S38SsRjiItdIdElgpqgzQDc8u7beqfdFRixnUvAsOf64zaRrQ2CjlwC1mdF8JRMAwIrovOjUK7TBfMg/ptu3+7na1v4xEQCnJq05TlsTDs9EDa9wI3R6rZZhW7/A2Y7F0XXPeMmACViKJaslQRXXD8ssyljnWEnX1Eq3+Trd4YmgkLG+NMtMqqT2NM=
